### ISSUE TITLE
Previous user chat is also appearing  when we use the same system(IP)

### ISSUE THREAD

**Issue by suresh4154** [v1bh0r/chantor#10]
This is the chat from one system with different users. 
    Previous user chat is also appearing when we use the same system(IP), Please check it
You 23/7/2012 18:54 hi
    kapil handa - 192.168.173.51 23/7/2012 18:54 hi
    You 23/7/2012 18:54 how are you
    kapil handa - 192.168.173.51 23/7/2012 18:54 fine thank u
    kapil handa - 192.168.173.51 23/7/2012 18:54 h r u?
    You 23/7/2012 18:54 good
    raj - 192.168.173.51 23/7/2012 18:55 check raj
    You 23/7/2012 18:55 how are you raj
    raj - 192.168.173.51 23/7/2012 18:55 m gud
    raj - 192.168.173.51 23/7/2012 18:55 h r u?
    You 23/7/2012 18:55 great
    arun - 192.168.173.51 23/7/2012 18:55 hello
    arun - 192.168.173.51 23/7/2012 18:55 arun this side
    You 23/7/2012 18:55 hi arun
    You 23/7/2012 18:55 h ru
    arun - 192.168.173.51 23/7/2012 18:55 all from one IP
    You 23/7/2012 18:56 but different names
    arun - 192.168.173.51 23/7/2012 18:56 yes
    You 23/7/2012 18:56 previous chat is also appering

**Comment by v1bh0r** [comment]
This is by design. Ip is the unique id.

**Comment by v1bh0r** [comment]
https://github.com/vibhor86/chantor/issues/11

**Comment by v1bh0r** [comment]
in new design employee code would be the identifier
